permalink:           pretty

title:               Sekretar
tagline:             'Hard and Soft'
url:                 http://blog.sekretar.im
baseurl:             ''
paginate:            1

author:
  name:              Yurii Sekretar
  url:               https://twitter.com/yuriisekretar
  email:             yuri.sekretar@gmail.com
  description:       Software developer

version:             1.0.0

github:
  repo:           https://github.com/yuriisekretar/yuriisekretar.github.io

gems:                [jekyll-paginate]
